# Generated by Django 5.0.2 on 2024-08-05 11:26

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag'),
    ]

    operations = [
        TrigramExtension()
    ]
